//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidiSequencer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MidiSequencer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize specified file, exception: .
        /// </summary>
        internal static string Cannot_deserialize_specified_file__exception__ {
            get {
                return ResourceManager.GetString("Cannot_deserialize_specified_file__exception__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot play note, exception: .
        /// </summary>
        internal static string Cannot_play_note__exception__ {
            get {
                return ResourceManager.GetString("Cannot_play_note__exception__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to midi in device .
        /// </summary>
        internal static string Cant_connect_to_midi_in_device {
            get {
                return ResourceManager.GetString("Cant_connect_to_midi_in_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to midi out device .
        /// </summary>
        internal static string Cant_connect_to_midi_out_device {
            get {
                return ResourceManager.GetString("Cant_connect_to_midi_out_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close called, stopping threads..
        /// </summary>
        internal static string Close_called__stopping_threads_ {
            get {
                return ResourceManager.GetString("Close_called__stopping_threads_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads stopped, closing application..
        /// </summary>
        internal static string Threads_stopped__closing_application_ {
            get {
                return ResourceManager.GetString("Threads_stopped__closing_application_", resourceCulture);
            }
        }
    }
}
