.TH "MidiSequencer/DrumSequence.xaml.cs" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer/DrumSequence.xaml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMidiSequencer\&.DrumSequence\fP"
.br
.RI "\fBSequence\fP type used for sequencing drums\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMidiSequencer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
