.TH "MidiSequencer Directory Reference" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApp\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBClockSequence\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBClockSequenceEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBClockStep\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBClockStepEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBColorPair\&.cs\fP"
.br
.ti -1c
.RI "file \fBCorruptedFileException\&.cs\fP"
.br
.ti -1c
.RI "file \fBDrumSequence\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBDrumSequenceEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBDrumStep\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBDrumStepEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainWindow\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBMidiInInterface\&.cs\fP"
.br
.ti -1c
.RI "file \fBMidiInterface\&.cs\fP"
.br
.ti -1c
.RI "file \fBMidiInterfaceEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBMidiOutInterface\&.cs\fP"
.br
.ti -1c
.RI "file \fBMonoSequence\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBMonoSequenceEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBMonoStep\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBMonoStepEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBPolySequence\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPolySequenceEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBPolyStep\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPolyStepEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBSequence\&.cs\fP"
.br
.ti -1c
.RI "file \fBSequenceEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBSequencer\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSequencerEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBSequenceTimer\&.cs\fP"
.br
.ti -1c
.RI "file \fBStep\&.cs\fP"
.br
.ti -1c
.RI "file \fBStepEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBToggleWithLabel\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBToolbar\&.xaml\&.cs\fP"
.br
.in -1c
