.TH "MidiSequencer.MonoStepEntity" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.MonoStepEntity \-  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMidiSequencer\&.StepEntity\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBOn\fP\fC [get, set]\fP"
.br
.RI "State of step\&. "
.ti -1c
.RI "int? \fBNote\fP\fC [get, set]\fP"
.br
.RI "Note recorded on step, null if no note recorded\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line 4 of file MonoStepEntity\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int? MidiSequencer\&.MonoStepEntity\&.Note\fC [get]\fP, \fC [set]\fP"

.PP
Note recorded on step, null if no note recorded\&. 
.PP
Definition at line 14 of file MonoStepEntity\&.cs\&.
.SS "bool MidiSequencer\&.MonoStepEntity\&.On\fC [get]\fP, \fC [set]\fP"

.PP
State of step\&. 
.PP
Definition at line 9 of file MonoStepEntity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
