.TH "MidiSequencer.DrumSequence" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.DrumSequence \- \fBSequence\fP type used for sequencing drums\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMidiSequencer\&.Sequence\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDrumSequence\fP (\fBSequencer\fP sequencer)"
.br
.ti -1c
.RI "override \fBSequenceEntity\fP \fBSerialize\fP ()"
.br
.RI "Serializes this instance of \fBSequence\fP\&. "
.ti -1c
.RI "override void \fBDeserialize\fP (\fBSequenceEntity\fP entity)"
.br
.RI "Deserializes sequence by applying values from passed serialized entity to this instance of \fBSequence\fP\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBReloadSteps\fP ()"
.br
.RI "Reloads steps if it's count changed\&. "
.ti -1c
.RI "override \fBColorPair\fP \fBSetup\fP ()"
.br
.RI "Creates a new \fBColorPair\fP of this type of sequence\&. "
.ti -1c
.RI "override void \fBRecordButton_Click\fP (object sender, RoutedEventArgs e)"
.br
.RI "Handles clicking record button\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBInNote\fP = 60\fC [get, set]\fP"
.br
.RI "Input note, default C4 (60) "
.ti -1c
.RI "int \fBOutNote\fP = 60\fC [get, set]\fP"
.br
.RI "Output note, default C4 (60) "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBSequence\fP type used for sequencing drums\&. 


.PP
Definition at line 12 of file DrumSequence\&.xaml\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MidiSequencer\&.DrumSequence\&.DrumSequence (\fBSequencer\fP sequencer)"

.PP

.PP
Definition at line 15 of file DrumSequence\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void MidiSequencer\&.DrumSequence\&.Deserialize (\fBSequenceEntity\fP entity)\fC [virtual]\fP"

.PP
Deserializes sequence by applying values from passed serialized entity to this instance of \fBSequence\fP\&. 
.PP
Implements \fBMidiSequencer\&.Sequence\fP\&.
.PP
Definition at line 81 of file DrumSequence\&.xaml\&.cs\&.
.SS "override void MidiSequencer\&.DrumSequence\&.RecordButton_Click (object sender, RoutedEventArgs e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Handles clicking record button\&. 
.PP
Implements \fBMidiSequencer\&.Sequence\fP\&.
.PP
Definition at line 58 of file DrumSequence\&.xaml\&.cs\&.
.SS "override void MidiSequencer\&.DrumSequence\&.ReloadSteps ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reloads steps if it's count changed\&. 
.PP
Implements \fBMidiSequencer\&.Sequence\fP\&.
.PP
Definition at line 41 of file DrumSequence\&.xaml\&.cs\&.
.SS "override \fBSequenceEntity\fP MidiSequencer\&.DrumSequence\&.Serialize ()\fC [virtual]\fP"

.PP
Serializes this instance of \fBSequence\fP\&. 
.PP
Implements \fBMidiSequencer\&.Sequence\fP\&.
.PP
Definition at line 64 of file DrumSequence\&.xaml\&.cs\&.
.SS "override \fBColorPair\fP MidiSequencer\&.DrumSequence\&.Setup ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Creates a new \fBColorPair\fP of this type of sequence\&. 
.PP
Implements \fBMidiSequencer\&.Sequence\fP\&.
.PP
Definition at line 47 of file DrumSequence\&.xaml\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int MidiSequencer\&.DrumSequence\&.InNote = 60\fC [get]\fP, \fC [set]\fP"

.PP
Input note, default C4 (60) 
.PP
Definition at line 33 of file DrumSequence\&.xaml\&.cs\&.
.SS "int MidiSequencer\&.DrumSequence\&.OutNote = 60\fC [get]\fP, \fC [set]\fP"

.PP
Output note, default C4 (60) 
.PP
Definition at line 38 of file DrumSequence\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
