.TH "MidiSequencer.SequenceEntity" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.SequenceEntity \- Serialized version of \fBSequence\fP, used for saving and loading from XML file\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMidiSequencer\&.ClockSequenceEntity\fP, \fBMidiSequencer\&.DrumSequenceEntity\fP, \fBMidiSequencer\&.MonoSequenceEntity\fP, and \fBMidiSequencer\&.PolySequenceEntity\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBType\fP\fC [get, set]\fP"
.br
.RI "Type of sequence this entity corresponds to\&. "
.ti -1c
.RI "int \fBGate\fP\fC [get, set]\fP"
.br
.RI "Gate time in milliseconds\&. "
.ti -1c
.RI "int \fBBeats\fP\fC [get, set]\fP"
.br
.RI "Amount of steps in bar\&. "
.ti -1c
.RI "int \fBBars\fP\fC [get, set]\fP"
.br
.RI "Amount og bars in sequence\&. "
.ti -1c
.RI "\fBMidiInterfaceEntity\fP \fBInput\fP\fC [get, set]\fP"
.br
.RI "Information about connected midi input device\&. "
.ti -1c
.RI "\fBMidiInterfaceEntity\fP \fBOutput\fP\fC [get, set]\fP"
.br
.RI "Information about connected midi output device\&. "
.in -1c
.SH "Detailed Description"
.PP 
Serialized version of \fBSequence\fP, used for saving and loading from XML file\&. 


.PP
Definition at line 6 of file SequenceEntity\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int MidiSequencer\&.SequenceEntity\&.Bars\fC [get]\fP, \fC [set]\fP"

.PP
Amount og bars in sequence\&. 
.PP
Definition at line 26 of file SequenceEntity\&.cs\&.
.SS "int MidiSequencer\&.SequenceEntity\&.Beats\fC [get]\fP, \fC [set]\fP"

.PP
Amount of steps in bar\&. 
.PP
Definition at line 21 of file SequenceEntity\&.cs\&.
.SS "int MidiSequencer\&.SequenceEntity\&.Gate\fC [get]\fP, \fC [set]\fP"

.PP
Gate time in milliseconds\&. 
.PP
Definition at line 16 of file SequenceEntity\&.cs\&.
.SS "\fBMidiInterfaceEntity\fP MidiSequencer\&.SequenceEntity\&.Input\fC [get]\fP, \fC [set]\fP"

.PP
Information about connected midi input device\&. 
.PP
Definition at line 31 of file SequenceEntity\&.cs\&.
.SS "\fBMidiInterfaceEntity\fP MidiSequencer\&.SequenceEntity\&.Output\fC [get]\fP, \fC [set]\fP"

.PP
Information about connected midi output device\&. 
.PP
Definition at line 36 of file SequenceEntity\&.cs\&.
.SS "string MidiSequencer\&.SequenceEntity\&.Type\fC [get]\fP, \fC [set]\fP"

.PP
Type of sequence this entity corresponds to\&. 
.PP
Definition at line 11 of file SequenceEntity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
