.TH "MidiSequencer.StepEntity" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.StepEntity \- Serialized \fBStep\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMidiSequencer\&.ClockStepEntity\fP, \fBMidiSequencer\&.DrumStepEntity\fP, \fBMidiSequencer\&.MonoStepEntity\fP, and \fBMidiSequencer\&.PolyStepEntity\fP\&.
.SH "Detailed Description"
.PP 
Serialized \fBStep\fP\&. 


.PP
Definition at line 6 of file StepEntity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
