.TH "MidiSequencer" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Logic of App\&.xaml "
.ti -1c
.RI "class \fBClockSequence\fP"
.br
.RI "Clock sequence UserControl "
.ti -1c
.RI "class \fBClockSequenceEntity\fP"
.br
.ti -1c
.RI "class \fBClockStep\fP"
.br
.RI "type of \fBStep\fP used by \fBClockSequence\fP\&. "
.ti -1c
.RI "class \fBClockStepEntity\fP"
.br
.ti -1c
.RI "struct \fBColorPair\fP"
.br
.RI "Holds pair of SolidColorBrush\&. "
.ti -1c
.RI "class \fBCorruptedFileException\fP"
.br
.ti -1c
.RI "class \fBDrumSequence\fP"
.br
.RI "\fBSequence\fP type used for sequencing drums\&. "
.ti -1c
.RI "class \fBDrumSequenceEntity\fP"
.br
.ti -1c
.RI "class \fBDrumStep\fP"
.br
.RI "type of \fBStep\fP used by \fBDrumSequence\fP\&. "
.ti -1c
.RI "class \fBDrumStepEntity\fP"
.br
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "Interaction logic for MainWindow\&.xaml "
.ti -1c
.RI "class \fBMidiInInterface\fP"
.br
.RI "Class used for interfacing with MIDI input devices "
.ti -1c
.RI "class \fBMidiInterface\fP"
.br
.RI "Abstract class for MIDI interfacing\&. "
.ti -1c
.RI "struct \fBMidiInterfaceEntity\fP"
.br
.RI "Class used for serialization of \fBMidiInterface\fP\&. "
.ti -1c
.RI "class \fBMidiOutInterface\fP"
.br
.RI "Class used for interfacing with MIDI output devices "
.ti -1c
.RI "class \fBMonoSequence\fP"
.br
.RI "\fBSequence\fP type used for monophonic instruments\&. "
.ti -1c
.RI "class \fBMonoSequenceEntity\fP"
.br
.ti -1c
.RI "class \fBMonoStep\fP"
.br
.RI "type of \fBStep\fP used by \fBMonoSequence\fP\&. "
.ti -1c
.RI "class \fBMonoStepEntity\fP"
.br
.ti -1c
.RI "class \fBPolySequence\fP"
.br
.RI "\fBSequence\fP type used for polyphonic instruments\&. "
.ti -1c
.RI "class \fBPolySequenceEntity\fP"
.br
.ti -1c
.RI "class \fBPolyStep\fP"
.br
.RI "type of \fBStep\fP used by \fBPolySequence\fP\&. "
.ti -1c
.RI "class \fBPolyStepEntity\fP"
.br
.ti -1c
.RI "class \fBSequence\fP"
.br
.RI "UserControl that is a base class for sequences\&. "
.ti -1c
.RI "class \fBSequenceEntity\fP"
.br
.RI "Serialized version of \fBSequence\fP, used for saving and loading from XML file\&. "
.ti -1c
.RI "class \fBSequencer\fP"
.br
.RI "UserControl that acts as a container for sequences\&. "
.ti -1c
.RI "class \fBSequencerEntity\fP"
.br
.RI "Entity class used for serialization\&. "
.ti -1c
.RI "class \fBSequenceTimer\fP"
.br
.ti -1c
.RI "class \fBStep\fP"
.br
.RI "Base UserControl for sequence's steps\&. "
.ti -1c
.RI "class \fBStepEntity\fP"
.br
.RI "Serialized \fBStep\fP\&. "
.ti -1c
.RI "class \fBToggleWithLabel\fP"
.br
.RI "UserControl representing a labeled ToggleButton "
.ti -1c
.RI "class \fBToolbar\fP"
.br
.RI "\fBToolbar\fP control used to edit individual sequences\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
