.TH "MidiSequencer.ClockSequence" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.ClockSequence \- Clock sequence UserControl  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMidiSequencer\&.Sequence\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClockSequence\fP (\fBSequencer\fP sequencer)"
.br
.ti -1c
.RI "void \fBReloadTimer\fP ()"
.br
.RI "Reloads timer, used when sequencer settings such as tempo changed\&. "
.ti -1c
.RI "void \fBStart\fP ()"
.br
.RI "Starts sequencer\&. "
.ti -1c
.RI "void \fBPause\fP ()"
.br
.RI "Pauses sequencer\&. "
.ti -1c
.RI "void \fBStop\fP ()"
.br
.RI "Stops sequencer\&. "
.ti -1c
.RI "override \fBSequenceEntity\fP \fBSerialize\fP ()"
.br
.RI "Serializes this instance of \fBSequence\fP\&. "
.ti -1c
.RI "override void \fBDeserialize\fP (\fBSequenceEntity\fP entity)"
.br
.RI "Deserializes sequence by applying values from passed serialized entity to this instance of \fBSequence\fP\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBReloadSteps\fP ()"
.br
.RI "Reloads steps if it's count changed\&. "
.ti -1c
.RI "override \fBColorPair\fP \fBSetup\fP ()"
.br
.RI "Creates a new \fBColorPair\fP of this type of sequence\&. "
.ti -1c
.RI "override void \fBRecordButton_Click\fP (object sender, RoutedEventArgs e)"
.br
.RI "Handles clicking record button\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Clock sequence UserControl 


.PP
Definition at line 11 of file ClockSequence\&.xaml\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MidiSequencer\&.ClockSequence\&.ClockSequence (\fBSequencer\fP sequencer)"

.PP

.PP
Definition at line 16 of file ClockSequence\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void MidiSequencer\&.ClockSequence\&.Deserialize (\fBSequenceEntity\fP entity)\fC [virtual]\fP"

.PP
Deserializes sequence by applying values from passed serialized entity to this instance of \fBSequence\fP\&. 
.PP
Implements \fBMidiSequencer\&.Sequence\fP\&.
.PP
Definition at line 109 of file ClockSequence\&.xaml\&.cs\&.
.SS "void MidiSequencer\&.ClockSequence\&.Pause ()"

.PP
Pauses sequencer\&. 
.PP
Definition at line 75 of file ClockSequence\&.xaml\&.cs\&.
.SS "override void MidiSequencer\&.ClockSequence\&.RecordButton_Click (object sender, RoutedEventArgs e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Handles clicking record button\&. 
.PP
Implements \fBMidiSequencer\&.Sequence\fP\&.
.PP
Definition at line 89 of file ClockSequence\&.xaml\&.cs\&.
.SS "override void MidiSequencer\&.ClockSequence\&.ReloadSteps ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reloads steps if it's count changed\&. 
.PP
Implements \fBMidiSequencer\&.Sequence\fP\&.
.PP
Definition at line 40 of file ClockSequence\&.xaml\&.cs\&.
.SS "void MidiSequencer\&.ClockSequence\&.ReloadTimer ()"

.PP
Reloads timer, used when sequencer settings such as tempo changed\&. 
.PP
Definition at line 59 of file ClockSequence\&.xaml\&.cs\&.
.SS "override \fBSequenceEntity\fP MidiSequencer\&.ClockSequence\&.Serialize ()\fC [virtual]\fP"

.PP
Serializes this instance of \fBSequence\fP\&. 
.PP
Implements \fBMidiSequencer\&.Sequence\fP\&.
.PP
Definition at line 95 of file ClockSequence\&.xaml\&.cs\&.
.SS "override \fBColorPair\fP MidiSequencer\&.ClockSequence\&.Setup ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Creates a new \fBColorPair\fP of this type of sequence\&. 
.PP
Implements \fBMidiSequencer\&.Sequence\fP\&.
.PP
Definition at line 46 of file ClockSequence\&.xaml\&.cs\&.
.SS "void MidiSequencer\&.ClockSequence\&.Start ()"

.PP
Starts sequencer\&. 
.PP
Definition at line 67 of file ClockSequence\&.xaml\&.cs\&.
.SS "void MidiSequencer\&.ClockSequence\&.Stop ()"

.PP
Stops sequencer\&. 
.PP
Definition at line 83 of file ClockSequence\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
