.TH "MidiSequencer.MidiInterfaceEntity" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.MidiInterfaceEntity \- Class used for serialization of \fBMidiInterface\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBChannel\fP\fC [get, set]\fP"
.br
.RI "MIDI channel\&. "
.ti -1c
.RI "int? \fBDevice\fP\fC [get, set]\fP"
.br
.RI "ID of MIDI device\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class used for serialization of \fBMidiInterface\fP\&. 


.PP
Definition at line 6 of file MidiInterfaceEntity\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int MidiSequencer\&.MidiInterfaceEntity\&.Channel\fC [get]\fP, \fC [set]\fP"

.PP
MIDI channel\&. 
.PP
Definition at line 11 of file MidiInterfaceEntity\&.cs\&.
.SS "int? MidiSequencer\&.MidiInterfaceEntity\&.Device\fC [get]\fP, \fC [set]\fP"

.PP
ID of MIDI device\&. 
.PP
Definition at line 16 of file MidiInterfaceEntity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
