.TH "MidiSequencer.MidiInterface" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.MidiInterface \- Abstract class for MIDI interfacing\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMidiSequencer\&.MidiInInterface\fP, and \fBMidiSequencer\&.MidiOutInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBConnectToDevice\fP (int deviceId)"
.br
.RI "Connects to device of specified id\&. "
.ti -1c
.RI "\fBMidiInterfaceEntity\fP \fBSerialize\fP ()"
.br
.RI "Creates simple object for serialization\&. "
.ti -1c
.RI "int? \fBGetDevice\fP ()"
.br
.RI "Returns device id\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int? \fBDevice\fP"
.br
.RI "ID of MIDI device\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBChannel\fP\fC [get, set]\fP"
.br
.RI "MIDI channel used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Abstract class for MIDI interfacing\&. 


.PP
Definition at line 6 of file MidiInterface\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract void MidiSequencer\&.MidiInterface\&.ConnectToDevice (int deviceId)\fC [pure virtual]\fP"

.PP
Connects to device of specified id\&. 
.PP
\fBParameters\fP
.RS 4
\fIdeviceId\fP ID of device to connect to\&.
.RE
.PP

.PP
Implemented in \fBMidiSequencer\&.MidiInInterface\fP, and \fBMidiSequencer\&.MidiOutInterface\fP\&.
.SS "int? MidiSequencer\&.MidiInterface\&.GetDevice ()"

.PP
Returns device id\&. 
.PP
\fBReturns\fP
.RS 4
Device id to which interface is connected if it is connected or null if it's not\&.
.RE
.PP

.PP
Definition at line 41 of file MidiInterface\&.cs\&.
.SS "\fBMidiInterfaceEntity\fP MidiSequencer\&.MidiInterface\&.Serialize ()"

.PP
Creates simple object for serialization\&. 
.PP
\fBReturns\fP
.RS 4
Object for serialization\&.
.RE
.PP

.PP
Definition at line 28 of file MidiInterface\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int? MidiSequencer\&.MidiInterface\&.Device\fC [protected]\fP"

.PP
ID of MIDI device\&. 
.PP
Definition at line 11 of file MidiInterface\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int MidiSequencer\&.MidiInterface\&.Channel\fC [get]\fP, \fC [set]\fP"

.PP
MIDI channel used\&. 
.PP
Definition at line 16 of file MidiInterface\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
