.TH "MidiSequencer.MidiInInterface" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.MidiInInterface \- Class used for interfacing with MIDI input devices  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMidiSequencer\&.MidiInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBConnectToDevice\fP (int deviceId)"
.br
.RI "Connects to device of specified id\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static MidiInCapabilities[] \fBGetMidiInDevices\fP ()"
.br
.RI "Gets connected MIDI input devices "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< MidiEvent > \fBEventPool\fP = new List<MidiEvent>()\fC [get]\fP"
.br
.RI "Stores unhandled received events\&. "
.ti -1c
.RI "int \fBNoteCount\fP\fC [get]\fP"
.br
.RI "Stores amount of notes that are currently on\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class used for interfacing with MIDI input devices 


.PP
Definition at line 11 of file MidiInInterface\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void MidiSequencer\&.MidiInInterface\&.ConnectToDevice (int deviceId)\fC [virtual]\fP"

.PP
Connects to device of specified id\&. 
.PP
Implements \fBMidiSequencer\&.MidiInterface\fP\&.
.PP
Definition at line 26 of file MidiInInterface\&.cs\&.
.SS "static MidiInCapabilities [] MidiSequencer\&.MidiInInterface\&.GetMidiInDevices ()\fC [static]\fP"

.PP
Gets connected MIDI input devices 
.PP
\fBReturns\fP
.RS 4
Array of MidiInCapabilities
.RE
.PP

.PP
Definition at line 60 of file MidiInInterface\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "List<MidiEvent> MidiSequencer\&.MidiInInterface\&.EventPool = new List<MidiEvent>()\fC [get]\fP"

.PP
Stores unhandled received events\&. 
.PP
Definition at line 18 of file MidiInInterface\&.cs\&.
.SS "int MidiSequencer\&.MidiInInterface\&.NoteCount\fC [get]\fP"

.PP
Stores amount of notes that are currently on\&. 
.PP
Definition at line 23 of file MidiInInterface\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
