.TH "MidiSequencer.DrumSequenceEntity" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.DrumSequenceEntity \-  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMidiSequencer\&.SequenceEntity\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBInNote\fP\fC [get, set]\fP"
.br
.RI "MIDI code for note that is used for input\&. "
.ti -1c
.RI "int \fBOutNote\fP\fC [get, set]\fP"
.br
.RI "MIDI code for note that is used for output\&. "
.ti -1c
.RI "\fBDrumStepEntity\fP[] \fBSteps\fP\fC [get, set]\fP"
.br
.RI "Array of steps\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line 7 of file DrumSequenceEntity\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int MidiSequencer\&.DrumSequenceEntity\&.InNote\fC [get]\fP, \fC [set]\fP"

.PP
MIDI code for note that is used for input\&. 
.PP
Definition at line 12 of file DrumSequenceEntity\&.cs\&.
.SS "int MidiSequencer\&.DrumSequenceEntity\&.OutNote\fC [get]\fP, \fC [set]\fP"

.PP
MIDI code for note that is used for output\&. 
.PP
Definition at line 17 of file DrumSequenceEntity\&.cs\&.
.SS "\fBDrumStepEntity\fP [] MidiSequencer\&.DrumSequenceEntity\&.Steps\fC [get]\fP, \fC [set]\fP"

.PP
Array of steps\&. 
.PP
Definition at line 22 of file DrumSequenceEntity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
