.TH "MidiSequencer.SequencerEntity" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.SequencerEntity \- Entity class used for serialization\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBBpm\fP\fC [get, set]\fP"
.br
.RI "Tempo in beats per minute\&. "
.ti -1c
.RI "\fBClockSequenceEntity\fP \fBClock\fP\fC [get, set]\fP"
.br
.RI "Serialized \fBClockSequence\fP "
.ti -1c
.RI "\fBSequenceEntity\fP[] \fBSequences\fP\fC [get, set]\fP"
.br
.RI "Array of serialized sequences\&. "
.in -1c
.SH "Detailed Description"
.PP 
Entity class used for serialization\&. 


.PP
Definition at line 8 of file SequencerEntity\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int MidiSequencer\&.SequencerEntity\&.Bpm\fC [get]\fP, \fC [set]\fP"

.PP
Tempo in beats per minute\&. 
.PP
Definition at line 13 of file SequencerEntity\&.cs\&.
.SS "\fBClockSequenceEntity\fP MidiSequencer\&.SequencerEntity\&.Clock\fC [get]\fP, \fC [set]\fP"

.PP
Serialized \fBClockSequence\fP 
.PP
Definition at line 18 of file SequencerEntity\&.cs\&.
.SS "\fBSequenceEntity\fP [] MidiSequencer\&.SequencerEntity\&.Sequences\fC [get]\fP, \fC [set]\fP"

.PP
Array of serialized sequences\&. 
.PP
Definition at line 26 of file SequencerEntity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
