.TH "MidiSequencer.Sequence" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.Sequence \- UserControl that is a base class for sequences\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UserControl\&.
.PP
Inherited by \fBMidiSequencer\&.ClockSequence\fP, \fBMidiSequencer\&.DrumSequence\fP, \fBMidiSequencer\&.MonoSequence\fP, and \fBMidiSequencer\&.PolySequence\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetHighlight\fP (bool highlighted)"
.br
.RI "Sets border highlight of sequence either on or off\&. "
.ti -1c
.RI "void \fBSetSteps\fP (int beats, int bars)"
.br
.RI "Sets amount of steps in sequence and reloads\&. "
.ti -1c
.RI "void \fBStopRecording\fP ()"
.br
.RI "Stops recording\&. "
.ti -1c
.RI "abstract \fBSequenceEntity\fP \fBSerialize\fP ()"
.br
.RI "Serializes this instance of \fBSequence\fP\&. "
.ti -1c
.RI "abstract void \fBDeserialize\fP (\fBSequenceEntity\fP entity)"
.br
.RI "Deserializes sequence by applying values from passed serialized entity to this instance of \fBSequence\fP\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBMidiInInterface\fP \fBInput\fP = new \fBMidiInInterface\fP()"
.br
.RI "Used to interact with MIDI input devices\&. "
.ti -1c
.RI "readonly \fBMidiOutInterface\fP \fBOutput\fP = new \fBMidiOutInterface\fP()"
.br
.RI "Used to interact with MIDI output devices\&. "
.ti -1c
.RI "bool? \fBHotRec\fP => HotRecButton\&.IsChecked"
.br
.RI "Property telling if hot recording is enabled\&. "
.ti -1c
.RI "bool? \fBOn\fP => OnButton\&.IsChecked"
.br
.RI "Property telling if sequence is enabled\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSequence\fP (\fBSequencer\fP sequencer)"
.br
.RI "Initializes sequence\&. "
.ti -1c
.RI "abstract void \fBRecordButton_Click\fP (object sender, RoutedEventArgs e)"
.br
.RI "Handles clicking record button\&. "
.ti -1c
.RI "abstract void \fBReloadSteps\fP ()"
.br
.RI "Reloads steps if it's count changed\&. "
.ti -1c
.RI "void \fBReloadSteps< T >\fP ()"
.br
.RI "Reloads steps if it's count changed\&. "
.ti -1c
.RI "abstract \fBColorPair\fP \fBSetup\fP ()"
.br
.RI "Creates a new \fBColorPair\fP of this type of sequence\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "readonly Button \fBEditButton\fP"
.br
.RI "Button that highlights sequence and opens it's toolbar\&. "
.ti -1c
.RI "readonly \fBToggleWithLabel\fP \fBHotRecButton\fP"
.br
.RI "Toggle button that when turned on records all inputs while sequence is playing\&. "
.ti -1c
.RI "readonly \fBToggleWithLabel\fP \fBOnButton\fP"
.br
.RI "Toggle button that when turned off disables all MIDI output of sequence\&. "
.ti -1c
.RI "readonly Button \fBRecordButton\fP"
.br
.RI "Button used to turn on recording\&. "
.ti -1c
.RI "readonly Button \fBRestButton\fP"
.br
.RI "Rest button used for recording sequence\&. "
.ti -1c
.RI "readonly \fBSequencer\fP \fBSequencer\fP"
.br
.RI "\fBSequencer\fP that hold this instance of \fBSequence\fP\&. "
.ti -1c
.RI "readonly VirtualizingStackPanel \fBStackPanel\fP"
.br
.RI "UI container holding elements of sequence\&. "
.ti -1c
.RI "Button \fBDeleteButton\fP"
.br
.RI "Button that removes sequence\&. "
.ti -1c
.RI "bool \fBRecording\fP"
.br
.RI "Field telling if recording is enabled\&. "
.ti -1c
.RI "bool \fBRest\fP"
.br
.RI "Field telling if rest button was clicked\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBGate\fP = 100\fC [get, set]\fP"
.br
.RI "Gate time of midi events in milliseconds\&. "
.ti -1c
.RI "int \fBBeats\fP = 4\fC [get, protected set]\fP"
.br
.RI "Amount of steps in a single bar\&. "
.ti -1c
.RI "int \fBBars\fP = 2\fC [get, protected set]\fP"
.br
.RI "Amount of bars in sequence\&. "
.ti -1c
.RI "List< \fBStep\fP > \fBSteps\fP = new List<\fBStep\fP>()\fC [get]\fP"
.br
.RI "List of sequence's steps\&. "
.in -1c
.SH "Detailed Description"
.PP 
UserControl that is a base class for sequences\&. 


.PP
Definition at line 13 of file Sequence\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MidiSequencer\&.Sequence\&.Sequence (\fBSequencer\fP sequencer)\fC [protected]\fP"

.PP
Initializes sequence\&. 
.PP
\fBParameters\fP
.RS 4
\fIsequencer\fP \fBSequencer\fP to which newly created sequence belongs\&.
.RE
.PP

.PP
Definition at line 83 of file Sequence\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract void MidiSequencer\&.Sequence\&.Deserialize (\fBSequenceEntity\fP entity)\fC [pure virtual]\fP"

.PP
Deserializes sequence by applying values from passed serialized entity to this instance of \fBSequence\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIentity\fP Serialized sequence
.RE
.PP

.PP
Implemented in \fBMidiSequencer\&.ClockSequence\fP, \fBMidiSequencer\&.PolySequence\fP, \fBMidiSequencer\&.MonoSequence\fP, and \fBMidiSequencer\&.DrumSequence\fP\&.
.SS "abstract void MidiSequencer\&.Sequence\&.RecordButton_Click (object sender, RoutedEventArgs e)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Handles clicking record button\&. 
.PP
\fBParameters\fP
.RS 4
\fIsender\fP 
.br
\fIe\fP 
.RE
.PP

.PP
Implemented in \fBMidiSequencer\&.ClockSequence\fP, \fBMidiSequencer\&.DrumSequence\fP, \fBMidiSequencer\&.MonoSequence\fP, and \fBMidiSequencer\&.PolySequence\fP\&.
.SS "abstract void MidiSequencer\&.Sequence\&.ReloadSteps ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Reloads steps if it's count changed\&. 
.PP
Implemented in \fBMidiSequencer\&.DrumSequence\fP, \fBMidiSequencer\&.ClockSequence\fP, \fBMidiSequencer\&.MonoSequence\fP, and \fBMidiSequencer\&.PolySequence\fP\&.
.SS "void \fBMidiSequencer\&.Sequence\&.ReloadSteps\fP< T > ()\fC [protected]\fP"

.PP
Reloads steps if it's count changed\&. 
.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fInew()\fP
.PP
Definition at line 258 of file Sequence\&.cs\&.
.SS "abstract \fBSequenceEntity\fP MidiSequencer\&.Sequence\&.Serialize ()\fC [pure virtual]\fP"

.PP
Serializes this instance of \fBSequence\fP\&. 
.PP
\fBReturns\fP
.RS 4
Serialized sequence
.RE
.PP

.PP
Implemented in \fBMidiSequencer\&.ClockSequence\fP, \fBMidiSequencer\&.PolySequence\fP, \fBMidiSequencer\&.MonoSequence\fP, and \fBMidiSequencer\&.DrumSequence\fP\&.
.SS "void MidiSequencer\&.Sequence\&.SetHighlight (bool highlighted)"

.PP
Sets border highlight of sequence either on or off\&. 
.PP
\fBParameters\fP
.RS 4
\fIhighlighted\fP Desired state of highlight\&.
.RE
.PP

.PP
Definition at line 228 of file Sequence\&.cs\&.
.SS "void MidiSequencer\&.Sequence\&.SetSteps (int beats, int bars)"

.PP
Sets amount of steps in sequence and reloads\&. 
.PP
\fBParameters\fP
.RS 4
\fIbeats\fP Amount of steps in a bar\&.
.br
\fIbars\fP Amount of bars in a sequence\&.
.RE
.PP

.PP
Definition at line 296 of file Sequence\&.cs\&.
.SS "abstract \fBColorPair\fP MidiSequencer\&.Sequence\&.Setup ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Creates a new \fBColorPair\fP of this type of sequence\&. 
.PP
\fBReturns\fP
.RS 4
\fBColorPair\fP of this type of sequence\&.
.RE
.PP

.PP
Implemented in \fBMidiSequencer\&.DrumSequence\fP, \fBMidiSequencer\&.ClockSequence\fP, \fBMidiSequencer\&.MonoSequence\fP, and \fBMidiSequencer\&.PolySequence\fP\&.
.SS "void MidiSequencer\&.Sequence\&.StopRecording ()"

.PP
Stops recording\&. 
.PP
Definition at line 307 of file Sequence\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Button MidiSequencer\&.Sequence\&.DeleteButton\fC [protected]\fP"

.PP
Button that removes sequence\&. 
.PP
Definition at line 67 of file Sequence\&.cs\&.
.SS "readonly Button MidiSequencer\&.Sequence\&.EditButton\fC [protected]\fP"

.PP
Button that highlights sequence and opens it's toolbar\&. 
.PP
Definition at line 22 of file Sequence\&.cs\&.
.SS "bool? MidiSequencer\&.Sequence\&.HotRec => HotRecButton\&.IsChecked"

.PP
Property telling if hot recording is enabled\&. 
.PP
Definition at line 178 of file Sequence\&.cs\&.
.SS "readonly \fBToggleWithLabel\fP MidiSequencer\&.Sequence\&.HotRecButton\fC [protected]\fP"

.PP
Toggle button that when turned on records all inputs while sequence is playing\&. 
.PP
Definition at line 27 of file Sequence\&.cs\&.
.SS "readonly \fBMidiInInterface\fP MidiSequencer\&.Sequence\&.Input = new \fBMidiInInterface\fP()"

.PP
Used to interact with MIDI input devices\&. 
.PP
Definition at line 32 of file Sequence\&.cs\&.
.SS "bool? MidiSequencer\&.Sequence\&.On => OnButton\&.IsChecked"

.PP
Property telling if sequence is enabled\&. 
.PP
Definition at line 183 of file Sequence\&.cs\&.
.SS "readonly \fBToggleWithLabel\fP MidiSequencer\&.Sequence\&.OnButton\fC [protected]\fP"

.PP
Toggle button that when turned off disables all MIDI output of sequence\&. 
.PP
Definition at line 37 of file Sequence\&.cs\&.
.SS "readonly \fBMidiOutInterface\fP MidiSequencer\&.Sequence\&.Output = new \fBMidiOutInterface\fP()"

.PP
Used to interact with MIDI output devices\&. 
.PP
Definition at line 42 of file Sequence\&.cs\&.
.SS "readonly Button MidiSequencer\&.Sequence\&.RecordButton\fC [protected]\fP"

.PP
Button used to turn on recording\&. 
.PP
Definition at line 47 of file Sequence\&.cs\&.
.SS "bool MidiSequencer\&.Sequence\&.Recording\fC [protected]\fP"

.PP
Field telling if recording is enabled\&. 
.PP
Definition at line 72 of file Sequence\&.cs\&.
.SS "bool MidiSequencer\&.Sequence\&.Rest\fC [protected]\fP"

.PP
Field telling if rest button was clicked\&. 
.PP
Definition at line 77 of file Sequence\&.cs\&.
.SS "readonly Button MidiSequencer\&.Sequence\&.RestButton\fC [protected]\fP"

.PP
Rest button used for recording sequence\&. 
.PP
Definition at line 52 of file Sequence\&.cs\&.
.SS "readonly \fBSequencer\fP MidiSequencer\&.Sequence\&.Sequencer\fC [protected]\fP"

.PP
\fBSequencer\fP that hold this instance of \fBSequence\fP\&. 
.PP
Definition at line 57 of file Sequence\&.cs\&.
.SS "readonly VirtualizingStackPanel MidiSequencer\&.Sequence\&.StackPanel\fC [protected]\fP"

.PP
UI container holding elements of sequence\&. 
.PP
Definition at line 62 of file Sequence\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int MidiSequencer\&.Sequence\&.Bars = 2\fC [get]\fP, \fC [protected set]\fP"

.PP
Amount of bars in sequence\&. 
.PP
Definition at line 198 of file Sequence\&.cs\&.
.SS "int MidiSequencer\&.Sequence\&.Beats = 4\fC [get]\fP, \fC [protected set]\fP"

.PP
Amount of steps in a single bar\&. 
.PP
Definition at line 193 of file Sequence\&.cs\&.
.SS "int MidiSequencer\&.Sequence\&.Gate = 100\fC [get]\fP, \fC [set]\fP"

.PP
Gate time of midi events in milliseconds\&. 
.PP
Definition at line 188 of file Sequence\&.cs\&.
.SS "List<\fBStep\fP> MidiSequencer\&.Sequence\&.Steps = new List<\fBStep\fP>()\fC [get]\fP"

.PP
List of sequence's steps\&. 
.PP
Definition at line 203 of file Sequence\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
