.TH "MidiSequencer.MainWindow" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.MainWindow \- Interaction logic for MainWindow\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP ()"
.br
.RI "Initializes window\&. "
.ti -1c
.RI "void \fBOpenToolbar\fP (\fBSequence\fP s)"
.br
.RI "Opens toolbar for specified sequence\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interaction logic for MainWindow\&.xaml 


.PP
Definition at line 15 of file MainWindow\&.xaml\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MidiSequencer\&.MainWindow\&.MainWindow ()"

.PP
Initializes window\&. 
.PP
Definition at line 20 of file MainWindow\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void MidiSequencer\&.MainWindow\&.OpenToolbar (\fBSequence\fP s)"

.PP
Opens toolbar for specified sequence\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP \fBSequence\fP for which to open toolbar\&.
.RE
.PP

.PP
Definition at line 118 of file MainWindow\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
