.TH "MidiSequencer.Toolbar" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.Toolbar \- \fBToolbar\fP control used to edit individual sequences\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UserControl\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToolbar\fP ()"
.br
.RI "Initializes control\&. "
.ti -1c
.RI "void \fBSetSequence\fP (\fBSequence\fP sequence)"
.br
.RI "Opens toolbar for passed sequence\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBToolbar\fP control used to edit individual sequences\&. 


.PP
Definition at line 14 of file Toolbar\&.xaml\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MidiSequencer\&.Toolbar\&.Toolbar ()"

.PP
Initializes control\&. 
.PP
Definition at line 36 of file Toolbar\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void MidiSequencer\&.Toolbar\&.SetSequence (\fBSequence\fP sequence)"

.PP
Opens toolbar for passed sequence\&. 
.PP
\fBParameters\fP
.RS 4
\fIsequence\fP \fBSequence\fP for which to open toolbar\&.
.RE
.PP

.PP
Definition at line 194 of file Toolbar\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
