.TH "MidiSequencer.MidiOutInterface" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.MidiOutInterface \- Class used for interfacing with MIDI output devices  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMidiSequencer\&.MidiInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMidiOutInterface\fP ()"
.br
.RI "Sets channel to 1, because default 0 is reserved for all channels\&. "
.ti -1c
.RI "override void \fBConnectToDevice\fP (int deviceId)"
.br
.RI "Connects to device of specified id\&. "
.ti -1c
.RI "void \fBSendEvent\fP (MidiEvent e)"
.br
.RI "Sends MIDI event to connected device\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static MidiOutCapabilities[] \fBGetMidiOutDevices\fP ()"
.br
.RI "Gets connected MIDI output devices "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class used for interfacing with MIDI output devices 


.PP
Definition at line 10 of file MidiOutInterface\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MidiSequencer\&.MidiOutInterface\&.MidiOutInterface ()"

.PP
Sets channel to 1, because default 0 is reserved for all channels\&. 
.PP
Definition at line 17 of file MidiOutInterface\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void MidiSequencer\&.MidiOutInterface\&.ConnectToDevice (int deviceId)\fC [virtual]\fP"

.PP
Connects to device of specified id\&. 
.PP
Implements \fBMidiSequencer\&.MidiInterface\fP\&.
.PP
Definition at line 23 of file MidiOutInterface\&.cs\&.
.SS "static MidiOutCapabilities [] MidiSequencer\&.MidiOutInterface\&.GetMidiOutDevices ()\fC [static]\fP"

.PP
Gets connected MIDI output devices 
.PP
\fBReturns\fP
.RS 4
Array of MidiOutCapabilities
.RE
.PP

.PP
Definition at line 48 of file MidiOutInterface\&.cs\&.
.SS "void MidiSequencer\&.MidiOutInterface\&.SendEvent (MidiEvent e)"

.PP
Sends MIDI event to connected device\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP MIDI event\&.
.RE
.PP

.PP
Definition at line 40 of file MidiOutInterface\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
