.TH "MidiSequencer.ToggleWithLabel" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.ToggleWithLabel \- UserControl representing a labeled ToggleButton  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UserControl\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToggleWithLabel\fP (string label)"
.br
.RI "Initializes Control\&. "
.ti -1c
.RI "void \fBSet\fP (bool val)"
.br
.RI "Sets value of toggle button irrespectively of current value\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool? \fBIsChecked\fP => _toggle\&.IsChecked"
.br
.RI "True if toggle is in ON position\&. "
.in -1c
.SH "Detailed Description"
.PP 
UserControl representing a labeled ToggleButton 


.PP
Definition at line 10 of file ToggleWithLabel\&.xaml\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MidiSequencer\&.ToggleWithLabel\&.ToggleWithLabel (string label)"

.PP
Initializes Control\&. 
.PP
\fBParameters\fP
.RS 4
\fIlabel\fP Label to be displayed below ToggleButton\&.
.RE
.PP

.PP
Definition at line 18 of file ToggleWithLabel\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void MidiSequencer\&.ToggleWithLabel\&.Set (bool val)"

.PP
Sets value of toggle button irrespectively of current value\&. 
.PP
\fBParameters\fP
.RS 4
\fIval\fP Value to which toggle is being set\&.
.RE
.PP

.PP
Definition at line 44 of file ToggleWithLabel\&.xaml\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool? MidiSequencer\&.ToggleWithLabel\&.IsChecked => _toggle\&.IsChecked"

.PP
True if toggle is in ON position\&. 
.PP
Definition at line 38 of file ToggleWithLabel\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
