.TH "MidiSequencer.App" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.App \- Logic of App\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SH "Detailed Description"
.PP 
Logic of App\&.xaml 


.PP
Definition at line 8 of file App\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
