.TH "MidiSequencer.ClockSequenceEntity" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.ClockSequenceEntity \-  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMidiSequencer\&.SequenceEntity\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
Definition at line 4 of file ClockSequenceEntity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
