.TH "MidiSequencer.ColorPair" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer.ColorPair \- Holds pair of SolidColorBrush\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SolidColorBrush \fBOn\fP"
.br
.RI "SolidColorBrush used for highlighted elements\&. "
.ti -1c
.RI "SolidColorBrush \fBOff\fP"
.br
.RI "SolidColorBrush used for not elements that are not highlighted\&. "
.in -1c
.SH "Detailed Description"
.PP 
Holds pair of SolidColorBrush\&. 


.PP
Definition at line 8 of file ColorPair\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "SolidColorBrush MidiSequencer\&.ColorPair\&.Off"

.PP
SolidColorBrush used for not elements that are not highlighted\&. 
.PP
Definition at line 18 of file ColorPair\&.cs\&.
.SS "SolidColorBrush MidiSequencer\&.ColorPair\&.On"

.PP
SolidColorBrush used for highlighted elements\&. 
.PP
Definition at line 13 of file ColorPair\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
