.TH "MidiSequencer/PolyStep.xaml.cs" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer/PolyStep.xaml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMidiSequencer\&.PolyStep\fP"
.br
.RI "type of \fBStep\fP used by \fBPolySequence\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMidiSequencer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
