.TH "MidiSequencer/Toolbar.xaml.cs" 3 "Wed Jun 10 2020" "MIDI Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiSequencer/Toolbar.xaml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMidiSequencer\&.Toolbar\fP"
.br
.RI "\fBToolbar\fP control used to edit individual sequences\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMidiSequencer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI Sequencer from the source code\&.
